apiVersion: v1
kind: Service
metadata:
    name: mongo
    labels:
        app: mongo
spec:
    selector:
        app: mongo
    ports:
        -   port: 27017
            targetPort: 27017
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: mongo
spec:
    serviceName: mongo
    replicas: 3
    selector:
        matchLabels:
            app: mongo
    template:
        metadata:
            labels:
                app: mongo
        spec:
            terminationGracePeriodSeconds: 10
            containers:
            -   name: mongo
                image: mongo
                env:
                    -   name: MONGO_INITDB_ROOT_USERNAME
                        value: admin
                    -   name: MONGO_INITDB_ROOT_PASSWORD
                        value: password                
                ports:
                    -   containerPort: 27017
                volumeMounts:
                    -   name: mongo-data
                        mountPath: /data/db
    volumeClaimTemplates:
        -   metadata:
                name: mongo-data
            spec:
                accessModes: [ "ReadWriteOnce" ]
                storageClassName: hostpath
                resources:
                    requests:
                        storage: 100Mi
