kind: Pod
apiVersion: v1
metadata:
    name: ui
    labels:
        app: ui_web
spec:
    containers:
        -   name: ui
            image: ehr/ui
            imagePullPolicy: IfNotPresent
            ports:
            -   containerPort: 80